name: Deploy Next.js Static Export to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read  # Changed from write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'  # Add caching

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js static site
        run: npm run build

      - name: Verify /out directory
        run: |
          if [ ! -d "out" ]; then
            echo "❌ ERROR: Export failed — /out directory not found."
            exit 1
          fi
          ls -la out/  # Show what's in the directory

      - name: Add deployment files
        run: |
          touch out/.nojekyll
          echo 'kittsmarketing.com' > out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true